package com.brainsmash.broken_world.registry.enums;

public enum OreColorRegistry {
    REDSTONE_ORE,
    DEEPSLATE_REDSTONE_ORE,
    COPPER_ORE,
    DEEPSLATE_COPPER_ORE,
    GOLD_ORE,
    NETHER_GOLD_ORE,
    DEEPSLATE_GOLD_ORE,
    IRON_ORE,
    DEEPSLATE_IRON_ORE,
    COAL_ORE,
    DEEPSLATE_COAL_ORE,
    EMERALD_ORE,
    DEEPSLATE_EMERALD_ORE,
    LAPIS_ORE,
    DEEPSLATE_LAPIS_ORE,
    DIAMOND_ORE,
    DEEPSLATE_DIAMOND_ORE,
    NETHER_QUARTZ_ORE,
    MOON_IRON_ORE,
    MOON_GOLD_ORE,
    MOON_REDSTONE_ORE,
    TUNGSTEN_ORE,

}
