package com.brainsmash.broken_world.enums;

public enum BlockRegistry {
    MOON_SAND,
    MOON_STONE,
    MOON_IRON_ORE,
    MOON_GOLD_ORE,
    TELEPORTER_FRAME,
    MOON_REDSTONE_ORE,
    MOON_SANDSTONE,
    RUSTY_METAL,
    TELEPORTER_CONTROLLER,
    MOON_TELEPORTER_FRAME,
    METALLIC_TELEPORTER_FRAME,
    TUNGSTEN_ORE,
    LUSH_TELEPORTER_FRAME,
    SULFURIC_STONE,
    SULFURIC_SOIL,
    SULFURIC_TELEPORTER_FRAME,
    COPPER_CABLE,
    CREATIVE_BATTERY,
    CREATIVE_GENERATOR,
    BASIC_MACHINE
}
